name = "Drifter"
uuid = "1e229871-6983-4c14-a913-6e2cca003bdc"
authors = ["Nick Boyd <nickboyd@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
